name: workflow_dispatch

on: push

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: c.rzp.io
        username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
        password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: c.rzp.io/razorpay/armory_traffic_outbound_${{ github.sha }}
